

output: SkeleKatze-Merged.kicad_mod
name: COMBINED_ART
layers:
  F.SilkS: SkeleKatze-Silk.kicad_mod
  F.Mask: SkeleKatze-Mask.kicad_mod
  F.Cu: SkeleKatze-Copper.kicad_mod
  B.Mask: SkeleKatze-Back-Mask.kicad_mod


